In [29]:
import pandas as pd
import numpy as np

In [30]:
data = pd.read_csv("Downloads/food_coded.csv")

In [31]:
data.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190

In [32]:
data.columns

Index(['GPA', 'Gender', 'breakfast', 'calories_chicken', 'calories_day',
       'calories_scone', 'coffee', 'comfort_food', 'comfort_food_reasons',
       'comfort_food_reasons_coded', 'cook', 'comfort_food_reasons_coded.1',
       'cuisine', 'diet_current', 'diet_current_coded', 'drink',
       'eating_changes', 'eating_changes_coded', 'eating_changes_coded1',
       'eating_out', 'employment', 'ethnic_food', 'exercise',
       'father_education', 'father_profession', 'fav_cuisine',
       'fav_cuisine_coded', 'fav_food', 'food_childhood', 'fries', 'fruit_day',
       'grade_level', 'greek_food', 'healthy_feeling', 'healthy_meal',
       'ideal_diet', 'ideal_diet_coded', 'income', 'indian_food',
       'italian_food', 'life_rewarding', 'marital_status',
       'meals_dinner_friend', 'mother_education', 'mother_profession',
       'nutritional_check', 'on_off_campus', 'parents_cook', 'pay_meal_out',
       'persian_food', 'self_perception_weight', 'soup', 'sports', 'thai_food',
       'tortilla_calories', 'turkey_calories', 'type_sports', 'veggies_day',
       'vitamins', 'waffle_calories', 'weight'],
      dtype='object')

In [33]:
data.isnull()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
121,False,False,False,False,False,False,False,False,False,True,...,False,True,False,False,False,False,False,False,False,False
122,False,False,False,False,True,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
123,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,True,False,False,False,False
124,False,False,False,False,True,False,False,False,False,True,...,False,False,False,False,False,True,False,False,False,False

In [34]:
data.iloc[:,1]

0      2
1      1
2      1
3      1
4      1
      ..
120    1
121    1
122    1
123    2
124    1
Name: Gender, Length: 125, dtype: int64

In [35]:
dup_cols = set()

for x in range(data.shape[1]):
    base_col = data.iloc[:,x]
    for y in range(x+1,data.shape[1]):
        comp_col = data.iloc[:,y]
        
        if base_col.equals(comp_col):
            dup_cols.add(data.columns.values[y])
            
print(dup_cols)

set()

In [36]:
data.drop(labels= dup_cols, axis=1)

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.5,1,1,610,4.0,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,NaN,...,1.0,1.0,5,940.0,500,Softball,5,1,1315,156
121,3,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,...,1.0,NaN,4,940.0,500,basketball,5,2,1315,180
122,3.882,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",sadness,NaN,...,1.0,2.0,5,580.0,690,none,4,2,1315,120
123,3,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,...,2.0,2.0,1,940.0,500,NaN,3,1,1315,135
124,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,...,1.0,2.0,2,725.0,345,NaN,4,2,575,135

In [37]:
data.isnull()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
121,False,False,False,False,False,False,False,False,False,True,...,False,True,False,False,False,False,False,False,False,False
122,False,False,False,False,True,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
123,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,True,False,False,False,False
124,False,False,False,False,True,False,False,False,False,True,...,False,False,False,False,False,True,False,False,False,False

In [38]:
data.isnull().sum()

GPA                  2
Gender               0
breakfast            0
calories_chicken     0
calories_day        19
                    ..
type_sports         21
veggies_day          0
vitamins             0
waffle_calories      0
weight               2
Length: 61, dtype: int64

In [39]:
data['type_sports'] = pd.to_numeric(data['type_sports'],errors='coerce')

In [40]:
# Impute missing type_sports with median (Numerical Variable)

data["type_sports"].fillna(data["type_sports"].median(), inplace = True)

In [41]:
# Impute missing type_sports with median (Numerical Variable)

data["calories_day"].fillna(data["calories_day"].mode() [0], inplace = True)

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    object
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  125 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    object
 8   comfort_food_reasons          124 non-null    object
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    object
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    object
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    object
 25  fav_cuisine                   123 non-null    object
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    object
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    object
 35  ideal_diet                    124 non-null    object
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    object
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    object
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   0 non-null      float64
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    object
dtypes: float64(21), int64(27), object(13)
memory usage: 59.7+ KB

In [43]:
data.isnull().sum()

GPA                   2
Gender                0
breakfast             0
calories_chicken      0
calories_day          0
                   ...
type_sports         125
veggies_day           0
vitamins              0
waffle_calories       0
weight                2
Length: 61, dtype: int64

In [44]:
# Impute missing type_sports with median (Numerical Variable)

data["type_sports"].fillna(data["type_sports"].mean(), inplace = True)

In [45]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    object
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  125 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    object
 8   comfort_food_reasons          124 non-null    object
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    object
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    object
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    object
 25  fav_cuisine                   123 non-null    object
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    object
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    object
 35  ideal_diet                    124 non-null    object
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    object
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    object
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   0 non-null      float64
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    object
dtypes: float64(21), int64(27), object(13)
memory usage: 59.7+ KB

In [46]:
data.isnull().sum()

GPA                   2
Gender                0
breakfast             0
calories_chicken      0
calories_day          0
                   ...
type_sports         125
veggies_day           0
vitamins              0
waffle_calories       0
weight                2
Length: 61, dtype: int64

In [47]:
# Using replace()
data["type_sports"].replace(np.NaN,data["type_sports"].mean(), inplace = True)

In [48]:
data["GPA"].replace(np.NaN,data["GPA"].mode() [0], inplace = True)

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           125 non-null    object
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  125 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    object
 8   comfort_food_reasons          124 non-null    object
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    object
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    object
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    object
 25  fav_cuisine                   123 non-null    object
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    object
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    object
 35  ideal_diet                    124 non-null    object
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    object
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    object
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   0 non-null      float64
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    object
dtypes: float64(21), int64(27), object(13)
memory usage: 59.7+ KB

In [50]:
data.isnull().sum()

GPA                   0
Gender                0
breakfast             0
calories_chicken      0
calories_day          0
                   ...
type_sports         125
veggies_day           0
vitamins              0
waffle_calories       0
weight                2
Length: 61, dtype: int64

In [51]:
data["weight"].replace(np.NaN,data["weight"].mode() [0], inplace = True)

In [53]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           125 non-null    object
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  125 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    object
 8   comfort_food_reasons          124 non-null    object
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    object
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    object
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    object
 25  fav_cuisine                   123 non-null    object
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    object
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    object
 35  ideal_diet                    124 non-null    object
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    object
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    object
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   0 non-null      float64
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        125 non-null    object
dtypes: float64(21), int64(27), object(13)
memory usage: 59.7+ KB

In [54]:
data.isnull().sum()

GPA                   0
Gender                0
breakfast             0
calories_chicken      0
calories_day          0
                   ...
type_sports         125
veggies_day           0
vitamins              0
waffle_calories       0
weight                0
Length: 61, dtype: int64

In [55]:
data = data.dropna(axis=1, how='all')

In [56]:
data.isnull().sum()

GPA                              0
Gender                           0
breakfast                        0
calories_chicken                 0
calories_day                     0
calories_scone                   1
coffee                           0
comfort_food                     1
comfort_food_reasons             1
comfort_food_reasons_coded      19
cook                             3
comfort_food_reasons_coded.1     0
cuisine                         17
diet_current                     1
diet_current_coded               0
drink                            2
eating_changes                   3
eating_changes_coded             0
eating_changes_coded1            0
eating_out                       0
employment                       9
ethnic_food                      0
exercise                        13
father_education                 1
father_profession                3
fav_cuisine                      2
fav_cuisine_coded                0
fav_food                         2
food_childhood                   1
fries                            0
fruit_day                        0
grade_level                      0
greek_food                       0
healthy_feeling                  0
healthy_meal                     1
ideal_diet                       1
ideal_diet_coded                 0
income                           1
indian_food                      0
italian_food                     0
life_rewarding                   1
marital_status                   1
meals_dinner_friend              3
mother_education                 3
mother_profession                2
nutritional_check                0
on_off_campus                    1
parents_cook                     0
pay_meal_out                     0
persian_food                     1
self_perception_weight           1
soup                             1
sports                           2
thai_food                        0
tortilla_calories                1
turkey_calories                  0
veggies_day                      0
vitamins                         0
waffle_calories                  0
weight                           0
dtype: int64

In [57]:
data["calories_day"].replace(np.NaN,data["calories_day"].mode() [0], inplace = True)

In [59]:
data["cuisine"].replace(np.NaN,data["cuisine"].mean(), inplace = True)

In [60]:
data["comfort_food_reasons_coded"].fillna(data["comfort_food_reasons_coded"].median(), inplace = True)

In [61]:
data["exercise"].fillna(data["exercise"].median(), inplace = True)

In [62]:
data["cook"].replace(np.NaN,data["cook"].mode() [0], inplace = True)

In [65]:
data["drink"].replace(np.NaN,data["drink"].mean(), inplace = True)

In [67]:
data["father_education"].fillna(data["father_education"].median(), inplace = True)

In [68]:
data["father_profession"].replace(np.NaN,data["father_profession"].mode() [0], inplace = True)

In [70]:
data["fav_food"].replace(np.NaN,data["fav_food"].mean(), inplace = True)

In [71]:
data["food_childhood"].replace(np.NaN,data["food_childhood"].mode() [0], inplace = True)

In [75]:
data["income"].fillna(data["income"].median(), inplace = True)

In [76]:
data["life_rewarding"].replace(np.NaN,data["life_rewarding"].mean(), inplace = True)

In [77]:
data["employment"].fillna(data["employment"].median(), inplace = True)

In [78]:
data["marital_status"].replace(np.NaN,data["marital_status"].mode() [0], inplace = True)

In [80]:
data["mother_education"].replace(np.NaN,data["mother_education"].mean(), inplace = True)

In [82]:
data["on_off_campus"].fillna(data["on_off_campus"].median(), inplace = True)

In [83]:
data["persian_food"].replace(np.NaN,data["persian_food"].mode() [0], inplace = True)

In [84]:
data["self_perception_weight"].replace(np.NaN,data["self_perception_weight"].mean(), inplace = True)

In [85]:
data["soup"].fillna(data["soup"].median(), inplace = True)

In [86]:
data["sports"].replace(np.NaN,data["sports"].mode() [0], inplace = True)

In [87]:
data["tortilla_calories"].replace(np.NaN,data["tortilla_calories"].mean(), inplace = True)

In [88]:
data.isnull().sum()

GPA                             0
Gender                          0
breakfast                       0
calories_chicken                0
calories_day                    0
calories_scone                  1
coffee                          0
comfort_food                    1
comfort_food_reasons            1
comfort_food_reasons_coded      0
cook                            0
comfort_food_reasons_coded.1    0
cuisine                         0
diet_current                    1
diet_current_coded              0
drink                           0
eating_changes                  3
eating_changes_coded            0
eating_changes_coded1           0
eating_out                      0
employment                      0
ethnic_food                     0
exercise                        0
father_education                0
father_profession               0
fav_cuisine                     2
fav_cuisine_coded               0
fav_food                        0
food_childhood                  0
fries                           0
fruit_day                       0
grade_level                     0
greek_food                      0
healthy_feeling                 0
healthy_meal                    1
ideal_diet                      1
ideal_diet_coded                0
income                          0
indian_food                     0
italian_food                    0
life_rewarding                  0
marital_status                  0
meals_dinner_friend             3
mother_education                0
mother_profession               2
nutritional_check               0
on_off_campus                   0
parents_cook                    0
pay_meal_out                    0
persian_food                    0
self_perception_weight          0
soup                            0
sports                          0
thai_food                       0
tortilla_calories               0
turkey_calories                 0
veggies_day                     0
vitamins                        0
waffle_calories                 0
weight                          0
dtype: int64

In [91]:
data = data.dropna(axis=1, thresh=1)

In [92]:
data.isnull().sum()

GPA                             0
Gender                          0
breakfast                       0
calories_chicken                0
calories_day                    0
calories_scone                  1
coffee                          0
comfort_food                    1
comfort_food_reasons            1
comfort_food_reasons_coded      0
cook                            0
comfort_food_reasons_coded.1    0
cuisine                         0
diet_current                    1
diet_current_coded              0
drink                           0
eating_changes                  3
eating_changes_coded            0
eating_changes_coded1           0
eating_out                      0
employment                      0
ethnic_food                     0
exercise                        0
father_education                0
father_profession               0
fav_cuisine                     2
fav_cuisine_coded               0
fav_food                        0
food_childhood                  0
fries                           0
fruit_day                       0
grade_level                     0
greek_food                      0
healthy_feeling                 0
healthy_meal                    1
ideal_diet                      1
ideal_diet_coded                0
income                          0
indian_food                     0
italian_food                    0
life_rewarding                  0
marital_status                  0
meals_dinner_friend             3
mother_education                0
mother_profession               2
nutritional_check               0
on_off_campus                   0
parents_cook                    0
pay_meal_out                    0
persian_food                    0
self_perception_weight          0
soup                            0
sports                          0
thai_food                       0
tortilla_calories               0
turkey_calories                 0
veggies_day                     0
vitamins                        0
waffle_calories                 0
weight                          0
dtype: int64

In [93]:
data.dropna(subset=['calories_scone'], inplace=True)

In [94]:
data.dropna(subset=['comfort_food'], inplace=True)

In [95]:
data.dropna(subset=['comfort_food_reasons'], inplace=True)

In [96]:
data.dropna(subset=['diet_current'], inplace=True)

In [97]:
data.dropna(subset=['eating_changes'], inplace=True)

In [98]:
data.dropna(subset=['fav_cuisine'], inplace=True)

In [99]:
data.dropna(subset=['healthy_meal'], inplace=True)

In [100]:
data.dropna(subset=['ideal_diet'], inplace=True)

In [101]:
data.dropna(subset=['meals_dinner_friend'], inplace=True)

In [102]:
data.dropna(subset=['mother_profession'], inplace=True)

In [103]:
data.isnull().sum()

GPA                             0
Gender                          0
breakfast                       0
calories_chicken                0
calories_day                    0
calories_scone                  0
coffee                          0
comfort_food                    0
comfort_food_reasons            0
comfort_food_reasons_coded      0
cook                            0
comfort_food_reasons_coded.1    0
cuisine                         0
diet_current                    0
diet_current_coded              0
drink                           0
eating_changes                  0
eating_changes_coded            0
eating_changes_coded1           0
eating_out                      0
employment                      0
ethnic_food                     0
exercise                        0
father_education                0
father_profession               0
fav_cuisine                     0
fav_cuisine_coded               0
fav_food                        0
food_childhood                  0
fries                           0
fruit_day                       0
grade_level                     0
greek_food                      0
healthy_feeling                 0
healthy_meal                    0
ideal_diet                      0
ideal_diet_coded                0
income                          0
indian_food                     0
italian_food                    0
life_rewarding                  0
marital_status                  0
meals_dinner_friend             0
mother_education                0
mother_profession               0
nutritional_check               0
on_off_campus                   0
parents_cook                    0
pay_meal_out                    0
persian_food                    0
self_perception_weight          0
soup                            0
sports                          0
thai_food                       0
tortilla_calories               0
turkey_calories                 0
veggies_day                     0
vitamins                        0
waffle_calories                 0
weight                          0
dtype: int64

In [104]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 118 entries, 0 to 124
Data columns (total 60 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           118 non-null    object
 1   Gender                        118 non-null    int64
 2   breakfast                     118 non-null    int64
 3   calories_chicken              118 non-null    int64
 4   calories_day                  118 non-null    float64
 5   calories_scone                118 non-null    float64
 6   coffee                        118 non-null    int64
 7   comfort_food                  118 non-null    object
 8   comfort_food_reasons          118 non-null    object
 9   comfort_food_reasons_coded    118 non-null    float64
 10  cook                          118 non-null    float64
 11  comfort_food_reasons_coded.1  118 non-null    int64
 12  cuisine                       118 non-null    float64
 13  diet_current                  118 non-null    object
 14  diet_current_coded            118 non-null    int64
 15  drink                         118 non-null    float64
 16  eating_changes                118 non-null    object
 17  eating_changes_coded          118 non-null    int64
 18  eating_changes_coded1         118 non-null    int64
 19  eating_out                    118 non-null    int64
 20  employment                    118 non-null    float64
 21  ethnic_food                   118 non-null    int64
 22  exercise                      118 non-null    float64
 23  father_education              118 non-null    float64
 24  father_profession             118 non-null    object
 25  fav_cuisine                   118 non-null    object
 26  fav_cuisine_coded             118 non-null    int64
 27  fav_food                      118 non-null    float64
 28  food_childhood                118 non-null    object
 29  fries                         118 non-null    int64
 30  fruit_day                     118 non-null    int64
 31  grade_level                   118 non-null    int64
 32  greek_food                    118 non-null    int64
 33  healthy_feeling               118 non-null    int64
 34  healthy_meal                  118 non-null    object
 35  ideal_diet                    118 non-null    object
 36  ideal_diet_coded              118 non-null    int64
 37  income                        118 non-null    float64
 38  indian_food                   118 non-null    int64
 39  italian_food                  118 non-null    int64
 40  life_rewarding                118 non-null    float64
 41  marital_status                118 non-null    float64
 42  meals_dinner_friend           118 non-null    object
 43  mother_education              118 non-null    float64
 44  mother_profession             118 non-null    object
 45  nutritional_check             118 non-null    int64
 46  on_off_campus                 118 non-null    float64
 47  parents_cook                  118 non-null    int64
 48  pay_meal_out                  118 non-null    int64
 49  persian_food                  118 non-null    float64
 50  self_perception_weight        118 non-null    float64
 51  soup                          118 non-null    float64
 52  sports                        118 non-null    float64
 53  thai_food                     118 non-null    int64
 54  tortilla_calories             118 non-null    float64
 55  turkey_calories               118 non-null    int64
 56  veggies_day                   118 non-null    int64
 57  vitamins                      118 non-null    int64
 58  waffle_calories               118 non-null    int64
 59  weight                        118 non-null    object
dtypes: float64(20), int64(27), object(13)
memory usage: 56.2+ KB